INFO 2021-06-01 16:58:47,921 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 16:58:50,218 basehttp  "GET /house/ HTTP/1.1" 200 12998
INFO 2021-06-01 16:58:59,887 basehttp  "GET /house/poliv/V24/ HTTP/1.1" 302 0
INFO 2021-06-01 16:58:59,924 basehttp  "GET /house/poliv/index/ HTTP/1.1" 200 4482
INFO 2021-06-01 16:59:12,826 basehttp  "GET /house/poliv/index/ HTTP/1.1" 200 4482
INFO 2021-06-01 16:59:22,276 basehttp  "GET /house/poliv/V24/ HTTP/1.1" 302 0
INFO 2021-06-01 16:59:22,403 basehttp  "GET /house/poliv/index/ HTTP/1.1" 200 4480
INFO 2021-06-01 16:59:23,572 basehttp  "GET /house/ HTTP/1.1" 200 12998
INFO 2021-06-01 17:01:01,028 basehttp  "GET /house/ HTTP/1.1" 200 12997
INFO 2021-06-01 17:02:44,869 autoreload  D:\SynologyDrive\my_smart_home\house\core\views.py changed, reloading.
INFO 2021-06-01 17:02:48,351 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:02:48,948 basehttp  "GET /house/poliv/V24/ HTTP/1.1" 302 0
INFO 2021-06-01 17:02:49,028 basehttp  "GET /house/poliv/index/ HTTP/1.1" 200 4482
INFO 2021-06-01 17:02:52,144 basehttp  "GET /house/ HTTP/1.1" 200 12997
INFO 2021-06-01 17:02:54,172 basehttp  "GET /house/poliv/V24/ HTTP/1.1" 302 0
INFO 2021-06-01 17:02:54,197 basehttp  "GET /house/poliv/index/ HTTP/1.1" 200 4480
INFO 2021-06-01 17:02:56,689 basehttp  "GET /house/ HTTP/1.1" 200 13007
ERROR 2021-06-01 17:04:31,820 log  Internal Server Error: /house/poliv/zapusk_poliva/
Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 559, in connect
    sock = self._connect()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 615, in _connect
    raise err
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 117, in reconnect_on_error
    yield
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 167, in _consume_from
    self._pubsub.subscribe(key)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\client.py", line 3580, in subscribe
    ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\client.py", line 3466, in execute_command
    self.connection = self.connection_pool.get_connection(
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 1192, in get_connection
    connection.connect()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 559, in connect
    sock = self._connect()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 615, in _connect
    raise err
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\kombu\connection.py", line 448, in _reraise_as_library_errors
    yield
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\app\base.py", line 717, in send_task
    self.backend.on_task_call(P, task_id)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 343, in on_task_call
    self.result_consumer.consume_from(task_id)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 159, in consume_from
    return self.start(task_id)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 137, in start
    self._consume_from(initial_task_id)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 167, in _consume_from
    self._pubsub.subscribe(key)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 120, in reconnect_on_error
    self._ensure(self._reconnect_pubsub, ())
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 354, in ensure
    return retry_over_time(
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\kombu\utils\functional.py", line 325, in retry_over_time
    return fun(*args, **kwargs)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 105, in _reconnect_pubsub
    metas = self.backend.client.mget(self.subscribed_to)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\client.py", line 1671, in mget
    return self.execute_command('MGET', *args, **options)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 1192, in get_connection
    connection.connect()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\SynologyDrive\my_smart_home\house\core\poliv_view.py", line 106, in zapusk_poliva
    poliv.apply_async()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\app\task.py", line 561, in apply_async
    return app.send_task(
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\app\base.py", line 718, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\kombu\connection.py", line 452, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
ERROR 2021-06-01 17:04:31,905 basehttp  "GET /house/poliv/zapusk_poliva/ HTTP/1.1" 500 237436
INFO 2021-06-01 17:04:56,512 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:04:58,054 basehttp  "GET /house/ HTTP/1.1" 200 13007
INFO 2021-06-01 17:05:54,495 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:05:55,266 basehttp  "GET /house/ HTTP/1.1" 200 13007
INFO 2021-06-01 17:06:51,457 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:06:58,096 basehttp  "GET /house/ HTTP/1.1" 200 13007
INFO 2021-06-01 17:07:10,271 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:08:29,844 autoreload  Watching for file changes with StatReloader
ERROR 2021-06-01 17:08:30,538 log  Internal Server Error: /house/poliv/zapusk_poliva/
Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\SynologyDrive\my_smart_home\house\core\poliv_view.py", line 106, in zapusk_poliva
    poliv.apply_async(name='task_watering_start_if_need')
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\app\task.py", line 561, in apply_async
    return app.send_task(
TypeError: send_task() got multiple values for argument 'name'
ERROR 2021-06-01 17:08:30,542 basehttp  "GET /house/poliv/zapusk_poliva/ HTTP/1.1" 500 79710
INFO 2021-06-01 17:09:08,211 autoreload  D:\SynologyDrive\my_smart_home\house\core\poliv_view.py changed, reloading.
INFO 2021-06-01 17:09:11,098 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:10:05,885 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:10:06,757 basehttp  "GET /house/ HTTP/1.1" 200 13008
INFO 2021-06-01 17:10:32,279 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:10:35,240 basehttp  "GET /house/ HTTP/1.1" 200 13008
INFO 2021-06-01 17:13:06,144 autoreload  D:\SynologyDrive\my_smart_home\house\core\poliv_view.py changed, reloading.
INFO 2021-06-01 17:13:11,489 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:13:34,836 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:14:14,645 autoreload  Watching for file changes with StatReloader
ERROR 2021-06-01 17:15:24,398 log  Internal Server Error: /house/poliv/zapusk_poliva/
Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 559, in connect
    sock = self._connect()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 615, in _connect
    raise err
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 117, in reconnect_on_error
    yield
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 167, in _consume_from
    self._pubsub.subscribe(key)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\client.py", line 3580, in subscribe
    ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\client.py", line 3466, in execute_command
    self.connection = self.connection_pool.get_connection(
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 1192, in get_connection
    connection.connect()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 559, in connect
    sock = self._connect()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 615, in _connect
    raise err
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\kombu\connection.py", line 448, in _reraise_as_library_errors
    yield
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\app\base.py", line 717, in send_task
    self.backend.on_task_call(P, task_id)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 343, in on_task_call
    self.result_consumer.consume_from(task_id)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 159, in consume_from
    return self.start(task_id)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 137, in start
    self._consume_from(initial_task_id)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 167, in _consume_from
    self._pubsub.subscribe(key)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 120, in reconnect_on_error
    self._ensure(self._reconnect_pubsub, ())
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 354, in ensure
    return retry_over_time(
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\kombu\utils\functional.py", line 325, in retry_over_time
    return fun(*args, **kwargs)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 105, in _reconnect_pubsub
    metas = self.backend.client.mget(self.subscribed_to)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\client.py", line 1671, in mget
    return self.execute_command('MGET', *args, **options)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 1192, in get_connection
    connection.connect()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\SynologyDrive\my_smart_home\house\core\poliv_view.py", line 106, in zapusk_poliva
    res = poliv.delay()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\app\task.py", line 421, in delay
    return self.apply_async(args, kwargs)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\app\task.py", line 561, in apply_async
    return app.send_task(
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\app\base.py", line 718, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\kombu\connection.py", line 452, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
ERROR 2021-06-01 17:15:24,461 basehttp  "GET /house/poliv/zapusk_poliva/ HTTP/1.1" 500 242011
INFO 2021-06-01 17:17:12,288 autoreload  D:\SynologyDrive\my_smart_home\house\core\poliv_view.py changed, reloading.
INFO 2021-06-01 17:17:15,643 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:18:52,359 autoreload  Watching for file changes with StatReloader
ERROR 2021-06-01 17:19:57,051 log  Internal Server Error: /house/poliv/zapusk_poliva/
Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 559, in connect
    sock = self._connect()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 615, in _connect
    raise err
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 117, in reconnect_on_error
    yield
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 167, in _consume_from
    self._pubsub.subscribe(key)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\client.py", line 3580, in subscribe
    ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\client.py", line 3466, in execute_command
    self.connection = self.connection_pool.get_connection(
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 1192, in get_connection
    connection.connect()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 559, in connect
    sock = self._connect()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 615, in _connect
    raise err
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\kombu\connection.py", line 448, in _reraise_as_library_errors
    yield
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\app\base.py", line 717, in send_task
    self.backend.on_task_call(P, task_id)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 343, in on_task_call
    self.result_consumer.consume_from(task_id)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 159, in consume_from
    return self.start(task_id)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 137, in start
    self._consume_from(initial_task_id)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 167, in _consume_from
    self._pubsub.subscribe(key)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 120, in reconnect_on_error
    self._ensure(self._reconnect_pubsub, ())
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 354, in ensure
    return retry_over_time(
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\kombu\utils\functional.py", line 325, in retry_over_time
    return fun(*args, **kwargs)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 105, in _reconnect_pubsub
    metas = self.backend.client.mget(self.subscribed_to)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\client.py", line 1671, in mget
    return self.execute_command('MGET', *args, **options)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 1192, in get_connection
    connection.connect()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\SynologyDrive\my_smart_home\house\core\poliv_view.py", line 106, in zapusk_poliva
    res = poliv.apply_async()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\app\task.py", line 561, in apply_async
    return app.send_task(
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\app\base.py", line 718, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\kombu\connection.py", line 452, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
ERROR 2021-06-01 17:19:57,066 basehttp  "GET /house/poliv/zapusk_poliva/ HTTP/1.1" 500 238007
INFO 2021-06-01 17:20:05,288 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-01 17:20:07,712 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:20:23,662 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-01 17:20:25,853 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:21:01,469 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:21:32,579 basehttp  "GET /house/ HTTP/1.1" 200 13007
INFO 2021-06-01 17:21:42,595 basehttp  "GET /house/solnce/ HTTP/1.1" 200 1594
ERROR 2021-06-01 17:22:10,226 log  Internal Server Error: /house/poliv/zapusk_poliva/
Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 559, in connect
    sock = self._connect()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 615, in _connect
    raise err
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 117, in reconnect_on_error
    yield
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 167, in _consume_from
    self._pubsub.subscribe(key)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\client.py", line 3580, in subscribe
    ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\client.py", line 3466, in execute_command
    self.connection = self.connection_pool.get_connection(
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 1192, in get_connection
    connection.connect()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 559, in connect
    sock = self._connect()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 615, in _connect
    raise err
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\kombu\connection.py", line 448, in _reraise_as_library_errors
    yield
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\app\base.py", line 717, in send_task
    self.backend.on_task_call(P, task_id)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 343, in on_task_call
    self.result_consumer.consume_from(task_id)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 159, in consume_from
    return self.start(task_id)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 137, in start
    self._consume_from(initial_task_id)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 167, in _consume_from
    self._pubsub.subscribe(key)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 120, in reconnect_on_error
    self._ensure(self._reconnect_pubsub, ())
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 354, in ensure
    return retry_over_time(
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\kombu\utils\functional.py", line 325, in retry_over_time
    return fun(*args, **kwargs)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 105, in _reconnect_pubsub
    metas = self.backend.client.mget(self.subscribed_to)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\client.py", line 1671, in mget
    return self.execute_command('MGET', *args, **options)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 1192, in get_connection
    connection.connect()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\SynologyDrive\my_smart_home\house\core\poliv_view.py", line 106, in zapusk_poliva
    poliv.delay(email="python@example.com")
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\app\task.py", line 421, in delay
    return self.apply_async(args, kwargs)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\app\task.py", line 561, in apply_async
    return app.send_task(
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\app\base.py", line 718, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\kombu\connection.py", line 452, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
ERROR 2021-06-01 17:22:10,308 basehttp  "GET /house/poliv/zapusk_poliva/ HTTP/1.1" 500 242722
INFO 2021-06-01 17:23:30,570 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:29:31,548 autoreload  D:\SynologyDrive\my_smart_home\house\core\poliv_view.py changed, reloading.
INFO 2021-06-01 17:29:37,685 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:33:37,304 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-01 17:33:43,032 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:34:46,345 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-01 17:34:49,941 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:46:13,632 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-01 17:46:19,022 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:46:55,538 autoreload  D:\SynologyDrive\my_smart_home\house\core\poliv_view.py changed, reloading.
INFO 2021-06-01 17:46:59,673 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:50:19,586 autoreload  D:\SynologyDrive\my_smart_home\house\core\poliv_view.py changed, reloading.
INFO 2021-06-01 17:50:23,840 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:53:39,260 autoreload  D:\SynologyDrive\my_smart_home\house\core\poliv_view.py changed, reloading.
INFO 2021-06-01 17:53:42,834 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 17:57:05,208 autoreload  D:\SynologyDrive\my_smart_home\house\core\main_arduino.py changed, reloading.
INFO 2021-06-01 17:57:09,675 autoreload  Watching for file changes with StatReloader
INFO 2021-06-01 18:08:24,497 autoreload  D:\SynologyDrive\my_smart_home\house\core\main_arduino.py changed, reloading.
INFO 2021-06-01 18:08:30,047 autoreload  Watching for file changes with StatReloader
INFO 2021-06-02 09:36:01,203 autoreload  Watching for file changes with StatReloader
INFO 2021-06-02 09:36:05,911 basehttp  "GET / HTTP/1.1" 200 17704
INFO 2021-06-02 09:36:22,460 basehttp  "GET /house/ HTTP/1.1" 200 12960
INFO 2021-06-02 09:36:22,562 basehttp  "GET /static/js/send_param.js HTTP/1.1" 304 0
INFO 2021-06-02 09:37:12,853 autoreload  Watching for file changes with StatReloader
INFO 2021-06-02 09:37:17,962 basehttp  "GET / HTTP/1.1" 200 17776
INFO 2021-06-02 09:37:18,162 basehttp  "GET / HTTP/1.1" 200 17776
INFO 2021-06-02 09:37:18,258 basehttp  "GET /static/start/css/custom.css HTTP/1.1" 200 2431
INFO 2021-06-02 09:37:19,696 basehttp  "GET /static/img/restoran.gif HTTP/1.1" 200 126582
INFO 2021-06-02 09:37:19,742 basehttp  "GET /static/img/ava_Alex.gif HTTP/1.1" 200 17631
INFO 2021-06-02 09:37:19,853 basehttp  "GET /static/img/flask.gif HTTP/1.1" 200 57553
INFO 2021-06-02 09:37:19,932 basehttp  "GET /static/img/smart_home2.gif HTTP/1.1" 200 20246
INFO 2021-06-02 09:37:19,964 basehttp  "GET /static/img/smart_home.gif HTTP/1.1" 200 47402
INFO 2021-06-02 09:37:19,987 basehttp  "GET /static/img/avto.gif HTTP/1.1" 200 11375
INFO 2021-06-02 09:37:20,083 basehttp  "GET /static/favico.ico HTTP/1.1" 200 15406
INFO 2021-06-02 09:37:30,174 basehttp  "GET /house/ HTTP/1.1" 200 12960
INFO 2021-06-02 09:37:43,189 basehttp  "GET /avto/ HTTP/1.1" 200 8536
INFO 2021-06-02 09:37:43,263 basehttp  "GET /static/selection_avto/css/start.css HTTP/1.1" 200 406
INFO 2021-06-02 09:37:43,691 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 2
INFO 2021-06-02 09:37:51,383 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 2
INFO 2021-06-02 09:37:52,703 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 2
INFO 2021-06-02 09:37:53,567 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 2
INFO 2021-06-02 09:37:53,923 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 2
INFO 2021-06-02 09:37:54,306 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 2
INFO 2021-06-02 09:37:54,843 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 2
INFO 2021-06-02 09:37:56,030 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 1
INFO 2021-06-02 09:37:56,035 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 1
INFO 2021-06-02 09:37:56,735 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 1
INFO 2021-06-02 09:37:56,796 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 1
INFO 2021-06-02 09:37:58,800 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 1
INFO 2021-06-02 09:37:59,813 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 1
INFO 2021-06-02 09:38:00,743 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 1
INFO 2021-06-02 09:38:01,477 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 1
INFO 2021-06-02 09:38:01,833 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 1
INFO 2021-06-02 09:38:05,543 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 1
INFO 2021-06-02 09:38:05,553 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 1
INFO 2021-06-02 09:38:06,658 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 1
INFO 2021-06-02 09:38:38,644 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 4
INFO 2021-06-02 09:38:41,376 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 4
INFO 2021-06-02 09:38:42,968 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 4
INFO 2021-06-02 09:38:43,977 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 4
INFO 2021-06-02 09:38:45,481 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 4
INFO 2021-06-02 09:38:49,894 basehttp  "POST /avto/ajax/ HTTP/1.1" 200 4
WARNING 2021-06-02 09:39:34,166 log  Not Found: //admin//config.php
WARNING 2021-06-02 09:39:34,167 basehttp  "GET //admin//config.php HTTP/1.1" 404 2583
WARNING 2021-06-02 09:40:09,173 log  Not Found: /admin//config.php
WARNING 2021-06-02 09:40:09,174 basehttp  "GET /admin//config.php HTTP/1.1" 404 2580
INFO 2021-06-02 15:17:59,360 autoreload  Watching for file changes with StatReloader
INFO 2021-06-02 15:18:33,282 autoreload  Watching for file changes with StatReloader
INFO 2021-06-02 15:19:32,933 autoreload  Watching for file changes with StatReloader
INFO 2021-06-02 15:19:56,959 autoreload  Watching for file changes with StatReloader
INFO 2021-06-02 15:23:14,916 autoreload  Watching for file changes with StatReloader
INFO 2021-06-02 15:23:20,270 basehttp  "GET / HTTP/1.1" 200 17776
INFO 2021-06-02 15:23:24,409 basehttp  "GET /house/ HTTP/1.1" 200 12940
WARNING 2021-06-02 15:23:24,696 log  Not Found: /favicon.ico
INFO 2021-06-02 15:23:30,169 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-02 15:23:30,501 basehttp  "GET /house/ HTTP/1.1" 200 13353
INFO 2021-06-02 15:25:00,346 autoreload  Watching for file changes with StatReloader
WARNING 2021-06-02 15:25:02,029 main_arduino  restart 5v
INFO 2021-06-02 15:25:03,886 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-02 15:25:04,345 basehttp  "GET /house/ HTTP/1.1" 200 13958
INFO 2021-06-02 15:28:37,372 autoreload  Watching for file changes with StatReloader
WARNING 2021-06-02 15:28:37,744 main_arduino  restart 5v
ERROR 2021-06-02 15:28:39,112 log  Internal Server Error: /house/temp/
Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\SynologyDrive\my_smart_home\house\core\views.py", line 131, in get
    arduino_task()  # читает датчики и занозит изменетия в БД
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\app\task.py", line 388, in __call__
    return self.run(*args, **kwargs)
  File "D:\SynologyDrive\my_smart_home\house\core\tasks.py", line 117, in arduino_task
    ackData=dic_param['ackData']
KeyError: 'ackData'
ERROR 2021-06-02 15:28:39,123 basehttp  "GET /house/temp/ HTTP/1.1" 500 100008
INFO 2021-06-02 15:30:14,488 autoreload  Watching for file changes with StatReloader
WARNING 2021-06-02 15:30:16,038 main_arduino  restart 5v
ERROR 2021-06-02 15:30:36,605 log  Internal Server Error: /house/temp/
Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\SynologyDrive\my_smart_home\house\core\views.py", line 131, in get
    arduino_task()  # читает датчики и занозит изменетия в БД
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\app\task.py", line 388, in __call__
    return self.run(*args, **kwargs)
  File "D:\SynologyDrive\my_smart_home\house\core\tasks.py", line 117, in arduino_task
    ackData=dic_param['ackData']
KeyError: 'ackData'
ERROR 2021-06-02 15:30:36,625 basehttp  "GET /house/temp/ HTTP/1.1" 500 102489
INFO 2021-06-02 15:33:10,882 autoreload  Watching for file changes with StatReloader
WARNING 2021-06-02 15:33:11,305 main_arduino  restart 5v
INFO 2021-06-02 15:33:13,756 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-02 15:33:14,277 basehttp  "GET /house/ HTTP/1.1" 200 13958
INFO 2021-06-02 15:33:15,437 basehttp  "GET /house/admin HTTP/1.1" 301 0
INFO 2021-06-02 15:33:15,501 basehttp  "GET /house/admin/ HTTP/1.1" 200 6058
INFO 2021-06-02 15:33:15,642 basehttp  "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
INFO 2021-06-02 15:33:15,646 basehttp  "GET /static/admin/css/base.css HTTP/1.1" 200 16307
INFO 2021-06-02 15:33:15,647 basehttp  "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 1360
INFO 2021-06-02 15:33:15,651 basehttp  "GET /static/admin/css/responsive.css HTTP/1.1" 200 18294
INFO 2021-06-02 15:33:15,653 basehttp  "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2138
INFO 2021-06-02 15:33:15,700 basehttp  "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
INFO 2021-06-02 15:33:15,764 basehttp  "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2021-06-02 15:33:15,765 basehttp  "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2021-06-02 15:33:15,786 basehttp  "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
INFO 2021-06-02 15:33:15,790 basehttp  "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
INFO 2021-06-02 15:33:15,815 basehttp  "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
INFO 2021-06-02 15:33:35,522 autoreload  Watching for file changes with StatReloader
INFO 2021-06-02 15:34:30,828 autoreload  D:\SynologyDrive\my_smart_home\house\core\admin.py changed, reloading.
INFO 2021-06-02 15:34:32,417 autoreload  Watching for file changes with StatReloader
INFO 2021-06-02 15:35:55,949 autoreload  Watching for file changes with StatReloader
INFO 2021-06-02 15:36:00,647 basehttp  "GET /house/admin/ HTTP/1.1" 200 6513
INFO 2021-06-02 15:36:02,112 basehttp  "GET /house/admin/core/params/ HTTP/1.1" 200 9876
INFO 2021-06-02 15:36:02,117 basehttp  "GET /static/admin/css/changelists.css HTTP/1.1" 200 6263
INFO 2021-06-02 15:36:02,124 basehttp  "GET /static/admin/js/actions.js HTTP/1.1" 200 6783
INFO 2021-06-02 15:36:02,136 basehttp  "GET /static/admin/js/urlify.js HTTP/1.1" 200 8632
INFO 2021-06-02 15:36:02,141 basehttp  "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2021-06-02 15:36:02,156 basehttp  "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
INFO 2021-06-02 15:36:02,160 basehttp  "GET /house/admin/jsi18n/ HTTP/1.1" 200 14892
INFO 2021-06-02 15:36:02,181 basehttp  "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 287630
INFO 2021-06-02 15:36:02,191 basehttp  "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2021-06-02 15:36:02,201 basehttp  "GET /static/admin/js/core.js HTTP/1.1" 200 5418
INFO 2021-06-02 15:36:02,208 basehttp  "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6078
INFO 2021-06-02 15:36:02,284 basehttp  "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2021-06-02 15:43:27,251 autoreload  D:\SynologyDrive\my_smart_home\house\core\admin.py changed, reloading.
INFO 2021-06-02 15:43:29,844 autoreload  Watching for file changes with StatReloader
INFO 2021-06-02 15:48:53,748 autoreload  Watching for file changes with StatReloader
INFO 2021-06-02 15:48:57,827 basehttp  "GET / HTTP/1.1" 200 17776
INFO 2021-06-02 15:49:11,825 basehttp  "GET /house/ HTTP/1.1" 200 13958
WARNING 2021-06-02 15:49:12,103 log  Not Found: /favicon.ico
WARNING 2021-06-02 15:49:14,086 main_arduino  restart 5v
INFO 2021-06-02 15:49:16,206 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-02 15:49:16,600 basehttp  "GET /house/ HTTP/1.1" 200 13957
INFO 2021-06-02 15:49:18,805 basehttp  "GET /house/admin/ HTTP/1.1" 200 6513
INFO 2021-06-02 15:49:21,741 basehttp  "GET /house/admin/core/dht_mq/ HTTP/1.1" 200 39993
INFO 2021-06-02 15:49:21,843 basehttp  "GET /house/admin/jsi18n/ HTTP/1.1" 200 14892
INFO 2021-06-02 15:49:34,087 basehttp  "GET /house/admin/ HTTP/1.1" 200 6513
INFO 2021-06-02 15:49:35,572 basehttp  "GET /house/admin/core/params/ HTTP/1.1" 200 7559
INFO 2021-06-02 15:49:35,684 basehttp  "GET /house/admin/jsi18n/ HTTP/1.1" 200 14892
INFO 2021-06-02 18:16:00,555 autoreload  Watching for file changes with StatReloader
INFO 2021-06-02 18:16:05,896 basehttp  "GET / HTTP/1.1" 200 17776
INFO 2021-06-02 18:16:10,112 basehttp  "GET /house/ HTTP/1.1" 200 14054
WARNING 2021-06-02 18:16:10,471 log  Not Found: /favicon.ico
INFO 2021-06-02 18:17:15,242 autoreload  Watching for file changes with StatReloader
INFO 2021-06-02 18:17:18,786 basehttp  "GET /house/ HTTP/1.1" 200 14054
WARNING 2021-06-02 18:17:28,988 main_arduino  restart 5v
INFO 2021-06-02 18:17:30,470 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-02 18:17:30,711 basehttp  "GET /house/ HTTP/1.1" 200 14054
INFO 2021-06-02 18:17:34,307 basehttp  "GET /house/ HTTP/1.1" 200 14054
INFO 2021-06-02 18:18:35,316 autoreload  Watching for file changes with StatReloader
INFO 2021-06-02 18:18:36,821 basehttp  "GET /house/ HTTP/1.1" 200 14054
INFO 2021-06-02 18:18:42,735 basehttp  "GET /house/ HTTP/1.1" 200 14054
INFO 2021-06-02 18:19:18,915 basehttp  "GET /house/ HTTP/1.1" 200 14022
INFO 2021-06-02 18:19:24,049 basehttp  "GET /house/ HTTP/1.1" 200 14021
WARNING 2021-06-02 18:19:51,146 main_arduino  restart 5v
INFO 2021-06-02 18:19:52,580 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-02 18:19:52,886 basehttp  "GET /house/ HTTP/1.1" 200 14021
INFO 2021-06-02 18:20:29,496 basehttp  "GET /house/ HTTP/1.1" 200 14021
INFO 2021-06-02 18:20:34,354 basehttp  "GET /house/ HTTP/1.1" 200 14021
INFO 2021-06-02 18:20:39,487 autoreload  Watching for file changes with StatReloader
INFO 2021-06-02 18:20:40,521 basehttp  "GET /house/ HTTP/1.1" 200 14021
INFO 2021-06-03 14:27:15,968 autoreload  Watching for file changes with StatReloader
INFO 2021-06-03 14:27:20,582 basehttp  "GET / HTTP/1.1" 200 17776
INFO 2021-06-03 14:27:21,303 basehttp  "GET /static/img/ava_Alex.gif HTTP/1.1" 304 0
INFO 2021-06-03 14:27:23,411 basehttp  "GET /house/ HTTP/1.1" 200 14047
INFO 2021-06-03 14:27:23,452 basehttp  "GET /static/js/send_param.js HTTP/1.1" 304 0
INFO 2021-06-03 14:27:43,459 basehttp  "GET /house/ HTTP/1.1" 200 14047
INFO 2021-06-03 14:28:56,815 basehttp  "GET /house/ HTTP/1.1" 200 14047
INFO 2021-06-03 14:29:11,419 basehttp  "GET /house/ HTTP/1.1" 200 14047
WARNING 2021-06-03 14:29:11,788 log  Not Found: /favicon.ico
INFO 2021-06-03 14:29:16,799 basehttp  "GET /house/ HTTP/1.1" 200 14047
INFO 2021-06-03 14:30:13,954 basehttp  "GET /house/ HTTP/1.1" 200 14048
WARNING 2021-06-03 14:30:14,296 log  Not Found: /favicon.ico
INFO 2021-06-03 14:31:41,641 basehttp  "GET /house/ HTTP/1.1" 200 14071
WARNING 2021-06-03 14:31:41,897 log  Not Found: /favicon.ico
INFO 2021-06-03 14:32:30,297 basehttp  "GET /house/ HTTP/1.1" 200 14071
INFO 2021-06-03 14:32:33,295 autoreload  D:\SynologyDrive\my_smart_home\house\core\views.py changed, reloading.
INFO 2021-06-03 14:32:35,763 autoreload  Watching for file changes with StatReloader
INFO 2021-06-03 14:32:37,073 basehttp  "GET /house/ HTTP/1.1" 200 14070
INFO 2021-06-03 14:32:59,801 basehttp  "GET /house/test/string_arduino_to_bot/?data HTTP/1.1" 200 338
INFO 2021-06-03 14:33:28,661 autoreload  D:\SynologyDrive\my_smart_home\house\core\DebagArduino.py changed, reloading.
INFO 2021-06-03 14:33:33,892 autoreload  Watching for file changes with StatReloader
INFO 2021-06-03 14:33:35,920 basehttp  "GET /house/ HTTP/1.1" 200 13963
WARNING 2021-06-03 14:33:38,248 main_arduino  restart 5v
INFO 2021-06-03 14:33:39,810 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-03 14:33:40,043 basehttp  "GET /house/ HTTP/1.1" 200 13963
INFO 2021-06-03 14:33:41,656 basehttp  "GET /house/ HTTP/1.1" 200 13963
INFO 2021-06-03 14:33:45,603 basehttp  "GET /house/ HTTP/1.1" 200 13963
INFO 2021-06-03 14:34:19,473 autoreload  Watching for file changes with StatReloader
INFO 2021-06-03 14:34:21,972 basehttp  "GET /house/ HTTP/1.1" 200 13963
WARNING 2021-06-03 14:35:33,609 main_arduino  restart 5v
INFO 2021-06-03 14:35:34,804 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-03 14:35:35,151 basehttp  "GET /house/ HTTP/1.1" 200 14038
INFO 2021-06-03 14:37:00,635 autoreload  Watching for file changes with StatReloader
WARNING 2021-06-03 14:38:45,435 main_arduino  restart 5v
WARNING 2021-06-03 14:38:45,437 main_arduino  restart 5v
INFO 2021-06-03 14:38:46,893 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-03 14:38:47,508 basehttp  "GET /house/ HTTP/1.1" 200 14186
WARNING 2021-06-03 14:38:55,099 main_arduino  restart 5v
INFO 2021-06-03 14:38:56,301 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-03 14:38:56,611 basehttp  "GET /house/ HTTP/1.1" 200 13813
WARNING 2021-06-03 14:39:07,491 main_arduino  restart 5v
INFO 2021-06-03 14:39:07,893 autoreload  D:\SynologyDrive\my_smart_home\house\core\DebagArduino.py changed, reloading.
INFO 2021-06-03 14:39:11,410 autoreload  Watching for file changes with StatReloader
WARNING 2021-06-03 14:39:12,274 main_arduino  restart 5v
INFO 2021-06-03 14:39:13,876 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-03 14:39:14,362 basehttp  "GET /house/ HTTP/1.1" 200 13797
INFO 2021-06-03 14:51:08,057 basehttp  "GET /house/ HTTP/1.1" 200 13797
INFO 2021-06-03 14:51:09,030 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-03 14:51:12,185 autoreload  Watching for file changes with StatReloader
INFO 2021-06-03 14:51:19,071 basehttp  "GET /house/ HTTP/1.1" 200 13797
INFO 2021-06-03 14:51:20,777 basehttp  "GET /house/ HTTP/1.1" 200 13797
INFO 2021-06-03 14:51:20,846 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 304 0
INFO 2021-06-03 14:51:20,921 basehttp  "GET /static/js/send_param.js HTTP/1.1" 304 0
INFO 2021-06-03 14:51:20,990 basehttp  "GET /static/img/home.gif HTTP/1.1" 304 0
INFO 2021-06-03 14:51:26,122 autoreload  Watching for file changes with StatReloader
INFO 2021-06-03 14:51:27,893 basehttp  "GET /house/ HTTP/1.1" 200 13797
INFO 2021-06-03 14:51:34,434 basehttp  "GET /house/ HTTP/1.1" 200 13797
INFO 2021-06-03 14:51:36,934 basehttp  "GET /house/admin/ HTTP/1.1" 200 6513
INFO 2021-06-03 14:51:37,074 basehttp  "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2021-06-03 14:51:37,124 basehttp  "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2021-06-03 14:51:38,824 basehttp  "GET /house/admin/core/setting/ HTTP/1.1" 200 13819
INFO 2021-06-03 14:51:38,907 basehttp  "GET /house/admin/jsi18n/ HTTP/1.1" 200 14892
INFO 2021-06-03 14:51:39,014 basehttp  "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2021-06-03 14:51:42,475 basehttp  "GET /house/admin/core/params/ HTTP/1.1" 200 7559
INFO 2021-06-03 14:51:42,546 basehttp  "GET /house/admin/jsi18n/ HTTP/1.1" 200 14892
INFO 2021-06-03 14:51:44,363 basehttp  "GET /house/admin/core/setting/ HTTP/1.1" 200 13819
INFO 2021-06-03 14:51:44,442 basehttp  "GET /house/admin/jsi18n/ HTTP/1.1" 200 14892
INFO 2021-06-03 14:51:52,675 basehttp  "GET /house/admin/core/params/ HTTP/1.1" 200 7559
INFO 2021-06-03 14:51:54,353 basehttp  "GET /house/admin/core/setting/ HTTP/1.1" 200 13819
INFO 2021-06-03 14:51:55,221 basehttp  "GET /house/admin/ HTTP/1.1" 200 6513
WARNING 2021-06-03 14:51:57,500 main_arduino  restart 5v
INFO 2021-06-03 14:51:59,072 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-03 14:51:59,365 basehttp  "GET /house/ HTTP/1.1" 200 13852
INFO 2021-06-03 14:52:33,095 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-03 14:52:35,070 autoreload  Watching for file changes with StatReloader
WARNING 2021-06-03 14:52:35,412 main_arduino  restart 5v
INFO 2021-06-03 14:52:36,906 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-03 14:52:37,452 basehttp  "GET /house/ HTTP/1.1" 200 13835
WARNING 2021-06-03 14:53:28,661 main_arduino  restart 5v
INFO 2021-06-03 14:53:29,193 autoreload  D:\SynologyDrive\my_smart_home\house\core\DebagArduino.py changed, reloading.
INFO 2021-06-03 14:53:31,038 autoreload  Watching for file changes with StatReloader
WARNING 2021-06-03 14:53:31,499 main_arduino  restart 5v
INFO 2021-06-03 14:53:32,933 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-03 14:53:33,320 basehttp  "GET /house/ HTTP/1.1" 200 13816
INFO 2021-06-03 14:54:17,160 basehttp  "GET /house/ HTTP/1.1" 200 13816
INFO 2021-06-03 14:54:17,498 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-03 14:54:21,327 autoreload  Watching for file changes with StatReloader
WARNING 2021-06-03 14:54:21,753 main_arduino  restart 5v
INFO 2021-06-03 14:54:23,516 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-03 14:54:24,087 basehttp  "GET /house/ HTTP/1.1" 200 13817
INFO 2021-06-03 14:55:09,686 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-03 14:55:11,399 autoreload  Watching for file changes with StatReloader
WARNING 2021-06-03 14:55:21,651 main_arduino  restart 5v
INFO 2021-06-03 14:55:23,485 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-03 14:55:24,686 basehttp  "GET /house/ HTTP/1.1" 200 13825
INFO 2021-06-03 14:55:54,241 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-03 14:55:56,282 autoreload  Watching for file changes with StatReloader
WARNING 2021-06-03 14:55:56,663 main_arduino  restart 5v
INFO 2021-06-03 14:55:58,117 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-03 14:55:58,497 basehttp  "GET /house/ HTTP/1.1" 200 13823
WARNING 2021-06-03 14:56:08,458 main_arduino  restart 5v
INFO 2021-06-03 14:56:08,982 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-03 14:56:10,661 autoreload  Watching for file changes with StatReloader
WARNING 2021-06-03 14:56:11,257 main_arduino  restart 5v
INFO 2021-06-03 14:56:12,920 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-03 14:56:13,317 basehttp  "GET /house/ HTTP/1.1" 200 13823
INFO 2021-06-03 14:56:41,735 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-03 14:56:43,468 autoreload  Watching for file changes with StatReloader
WARNING 2021-06-03 14:56:43,986 main_arduino  restart 5v
INFO 2021-06-03 14:56:45,688 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-03 14:56:46,321 basehttp  "GET /house/ HTTP/1.1" 200 13819
WARNING 2021-06-03 14:57:15,875 main_arduino  restart 5v
INFO 2021-06-03 14:57:16,199 autoreload  D:\SynologyDrive\my_smart_home\house\core\DebagArduino.py changed, reloading.
INFO 2021-06-03 14:57:18,052 autoreload  Watching for file changes with StatReloader
WARNING 2021-06-03 14:57:18,488 main_arduino  restart 5v
INFO 2021-06-03 14:57:20,149 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-03 14:57:20,546 basehttp  "GET /house/ HTTP/1.1" 200 13789
INFO 2021-06-03 14:58:07,018 basehttp  "GET /house/ HTTP/1.1" 200 13805
INFO 2021-06-03 14:58:19,285 basehttp  "GET /house/ HTTP/1.1" 200 13805
INFO 2021-06-03 14:58:19,419 autoreload  D:\SynologyDrive\my_smart_home\house\core\DebagArduino.py changed, reloading.
INFO 2021-06-03 14:58:22,130 autoreload  Watching for file changes with StatReloader
WARNING 2021-06-03 14:58:22,518 main_arduino  restart 5v
INFO 2021-06-03 14:58:24,107 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-03 14:58:24,626 basehttp  "GET /house/ HTTP/1.1" 200 13837
INFO 2021-06-03 15:08:45,220 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-03 15:08:48,174 autoreload  Watching for file changes with StatReloader
INFO 2021-06-03 15:09:12,416 basehttp  "GET /house/poliv/index/ HTTP/1.1" 200 4480
INFO 2021-06-03 15:09:12,563 basehttp  "GET /static/css/poliv.css HTTP/1.1" 200 1208
WARNING 2021-06-03 15:09:12,869 log  Not Found: /favicon.ico
INFO 2021-06-03 15:10:14,602 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-03 15:10:16,765 autoreload  Watching for file changes with StatReloader
INFO 2021-06-03 15:17:17,708 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-03 15:17:19,878 autoreload  Watching for file changes with StatReloader
INFO 2021-06-03 15:18:29,112 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-03 15:18:32,061 autoreload  Watching for file changes with StatReloader
INFO 2021-06-03 15:18:34,611 basehttp  "GET /house/ HTTP/1.1" 200 13837
INFO 2021-06-03 15:18:37,406 basehttp  "GET /house/admin/ HTTP/1.1" 200 6513
INFO 2021-06-03 15:18:55,684 basehttp  "GET /house/admin/core/params/ HTTP/1.1" 200 7559
INFO 2021-06-03 15:18:55,761 basehttp  "GET /house/admin/jsi18n/ HTTP/1.1" 200 14892
INFO 2021-06-03 15:18:57,153 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-03 15:19:00,466 autoreload  Watching for file changes with StatReloader
INFO 2021-06-03 15:20:42,037 autoreload  Watching for file changes with StatReloader
INFO 2021-06-03 15:20:42,985 basehttp  "GET /house/admin/ HTTP/1.1" 200 6513
INFO 2021-06-03 15:20:48,118 basehttp  "GET /house/poliv/index/ HTTP/1.1" 200 4480
INFO 2021-06-03 15:21:51,077 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-03 15:21:54,556 autoreload  Watching for file changes with StatReloader
ERROR 2021-06-03 15:23:02,126 log  Internal Server Error: /house/poliv/zapusk_poliva/
Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 559, in connect
    sock = self._connect()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 615, in _connect
    raise err
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 117, in reconnect_on_error
    yield
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 167, in _consume_from
    self._pubsub.subscribe(key)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\client.py", line 3580, in subscribe
    ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\client.py", line 3466, in execute_command
    self.connection = self.connection_pool.get_connection(
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 1192, in get_connection
    connection.connect()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 559, in connect
    sock = self._connect()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 615, in _connect
    raise err
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\kombu\connection.py", line 448, in _reraise_as_library_errors
    yield
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\app\base.py", line 717, in send_task
    self.backend.on_task_call(P, task_id)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 343, in on_task_call
    self.result_consumer.consume_from(task_id)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 159, in consume_from
    return self.start(task_id)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 137, in start
    self._consume_from(initial_task_id)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 167, in _consume_from
    self._pubsub.subscribe(key)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 120, in reconnect_on_error
    self._ensure(self._reconnect_pubsub, ())
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 354, in ensure
    return retry_over_time(
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\kombu\utils\functional.py", line 325, in retry_over_time
    return fun(*args, **kwargs)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\backends\redis.py", line 105, in _reconnect_pubsub
    metas = self.backend.client.mget(self.subscribed_to)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\client.py", line 1671, in mget
    return self.execute_command('MGET', *args, **options)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 1192, in get_connection
    connection.connect()
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\redis\connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\SynologyDrive\my_smart_home\house\core\poliv_view.py", line 106, in zapusk_poliva
    poliv.delay(force=True)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\app\task.py", line 421, in delay
    return self.apply_async(args, kwargs)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\app\task.py", line 561, in apply_async
    return app.send_task(
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\celery\app\base.py", line 718, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Alex\.virtualenvs\my_smart_home\lib\site-packages\kombu\connection.py", line 452, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
ERROR 2021-06-03 15:23:02,194 basehttp  "GET /house/poliv/zapusk_poliva/ HTTP/1.1" 500 242417
WARNING 2021-06-03 15:23:02,472 log  Not Found: /favicon.ico
INFO 2021-06-03 15:33:29,312 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-03 15:33:33,611 autoreload  Watching for file changes with StatReloader
INFO 2021-06-03 15:34:44,525 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-03 15:34:46,490 autoreload  Watching for file changes with StatReloader
INFO 2021-06-03 15:39:58,766 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-03 15:40:01,291 autoreload  Watching for file changes with StatReloader
INFO 2021-06-03 15:43:12,133 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-03 15:43:14,923 autoreload  Watching for file changes with StatReloader
INFO 2021-06-04 17:27:48,547 autoreload  Watching for file changes with StatReloader
INFO 2021-06-04 17:27:53,869 basehttp  "GET / HTTP/1.1" 200 17776
INFO 2021-06-04 17:27:54,437 basehttp  "GET /static/start/css/custom.css HTTP/1.1" 304 0
INFO 2021-06-04 17:27:54,670 basehttp  "GET /static/img/avto.gif HTTP/1.1" 304 0
INFO 2021-06-04 17:27:54,700 basehttp  "GET /static/img/smart_home.gif HTTP/1.1" 304 0
INFO 2021-06-04 17:27:54,703 basehttp  "GET /static/img/smart_home2.gif HTTP/1.1" 304 0
INFO 2021-06-04 17:27:54,716 basehttp  "GET /static/img/flask.gif HTTP/1.1" 304 0
INFO 2021-06-04 17:27:54,722 basehttp  "GET /static/img/restoran.gif HTTP/1.1" 304 0
INFO 2021-06-04 17:27:57,035 basehttp  "GET /house/ HTTP/1.1" 200 14321
INFO 2021-06-04 17:27:57,099 basehttp  "GET /static/css/main.css HTTP/1.1" 304 0
INFO 2021-06-04 17:27:57,118 basehttp  "GET /static/js/send_param.js HTTP/1.1" 304 0
WARNING 2021-06-04 17:28:02,276 main_arduino  restart 5v
INFO 2021-06-04 17:28:03,752 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-04 17:28:05,007 basehttp  "GET /house/ HTTP/1.1" 200 14321
WARNING 2021-06-04 17:28:17,171 main_arduino  restart 5v
INFO 2021-06-04 17:28:18,677 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-04 17:28:18,953 basehttp  "GET /house/ HTTP/1.1" 200 14321
INFO 2021-06-04 17:29:30,171 autoreload  Watching for file changes with StatReloader
WARNING 2021-06-04 17:29:32,252 main_arduino  restart 5v
INFO 2021-06-04 17:29:33,767 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-04 17:29:34,214 basehttp  "GET /house/ HTTP/1.1" 200 14321
INFO 2021-06-04 17:30:50,066 autoreload  Watching for file changes with StatReloader
WARNING 2021-06-04 17:31:51,609 main_arduino  restart 5v
INFO 2021-06-04 17:32:48,343 autoreload  Watching for file changes with StatReloader
INFO 2021-06-04 17:33:35,429 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-04 17:33:39,418 basehttp  "GET /house/ HTTP/1.1" 200 13999
INFO 2021-06-04 17:37:02,248 autoreload  Watching for file changes with StatReloader
INFO 2021-06-04 17:37:03,253 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 304 0
INFO 2021-06-04 17:37:03,264 basehttp  "GET /static/js/send_param.js HTTP/1.1" 304 0
INFO 2021-06-04 17:37:03,274 basehttp  "GET /house/ HTTP/1.1" 200 13999
INFO 2021-06-04 17:37:03,344 basehttp  "GET /static/img/home.gif HTTP/1.1" 304 0
INFO 2021-06-04 17:37:04,358 basehttp  "GET /house/ HTTP/1.1" 200 13999
INFO 2021-06-04 17:37:04,404 basehttp  "GET /static/js/send_param.js HTTP/1.1" 304 0
INFO 2021-06-04 17:37:04,406 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 304 0
INFO 2021-06-04 17:37:04,459 basehttp  "GET /static/img/home.gif HTTP/1.1" 304 0
INFO 2021-06-04 17:37:05,950 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-04 17:37:06,221 basehttp  "GET /house/ HTTP/1.1" 200 13999
INFO 2021-06-04 17:37:35,796 autoreload  D:\SynologyDrive\my_smart_home\house\core\DebagArduino.py changed, reloading.
INFO 2021-06-04 17:37:37,605 autoreload  Watching for file changes with StatReloader
INFO 2021-06-04 17:37:38,902 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-04 17:37:39,358 basehttp  "GET /house/ HTTP/1.1" 200 13999
INFO 2021-06-04 17:37:47,045 autoreload  D:\SynologyDrive\my_smart_home\house\core\DebagArduino.py changed, reloading.
INFO 2021-06-04 17:37:49,440 autoreload  Watching for file changes with StatReloader
INFO 2021-06-04 17:37:50,470 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-04 17:37:50,869 basehttp  "GET /house/ HTTP/1.1" 200 13999
INFO 2021-06-04 17:38:00,335 autoreload  D:\SynologyDrive\my_smart_home\house\core\DebagArduino.py changed, reloading.
INFO 2021-06-04 17:38:02,311 autoreload  Watching for file changes with StatReloader
INFO 2021-06-04 17:38:03,218 basehttp  "GET /house/temp/ HTTP/1.1" 302 0
INFO 2021-06-04 17:38:03,630 basehttp  "GET /house/ HTTP/1.1" 200 13999
INFO 2021-06-04 17:39:13,004 basehttp  "GET /house/ HTTP/1.1" 200 13948
INFO 2021-06-04 17:40:11,664 basehttp  "GET /house/ HTTP/1.1" 200 13999
INFO 2021-06-04 17:40:42,004 basehttp  "GET /house/ HTTP/1.1" 200 13982
INFO 2021-06-04 17:40:42,118 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 304 0
INFO 2021-06-04 17:40:42,197 basehttp  "GET /static/js/send_param.js HTTP/1.1" 304 0
INFO 2021-06-04 17:40:42,283 basehttp  "GET /static/img/home.gif HTTP/1.1" 200 114599
INFO 2021-06-04 17:41:33,264 basehttp  "GET /house/ HTTP/1.1" 200 13965
INFO 2021-06-04 17:44:00,018 basehttp  "GET /house/ HTTP/1.1" 200 13846
INFO 2021-06-04 17:44:23,619 basehttp  "GET /house/ HTTP/1.1" 200 13863
INFO 2021-06-04 17:46:57,003 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-04 17:46:59,655 autoreload  Watching for file changes with StatReloader
INFO 2021-06-04 17:52:37,466 autoreload  D:\SynologyDrive\my_smart_home\house\core\analiz.py changed, reloading.
INFO 2021-06-04 17:52:40,862 autoreload  Watching for file changes with StatReloader
INFO 2021-06-04 17:56:40,554 autoreload  Watching for file changes with StatReloader
INFO 2021-06-04 17:56:46,455 basehttp  "GET /house/admin/ HTTP/1.1" 200 6513
INFO 2021-06-04 17:56:46,700 basehttp  "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2021-06-04 17:56:46,714 basehttp  "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2021-06-04 17:56:49,830 basehttp  "GET /house/admin/core/params/ HTTP/1.1" 200 7785
INFO 2021-06-04 17:56:49,900 basehttp  "GET /house/admin/jsi18n/ HTTP/1.1" 200 14892
INFO 2021-06-04 17:56:50,043 basehttp  "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2021-06-04 17:59:44,672 autoreload  D:\SynologyDrive\my_smart_home\house\core\tasks.py changed, reloading.
INFO 2021-06-04 17:59:46,629 autoreload  Watching for file changes with StatReloader
INFO 2021-06-07 13:18:07,503 autoreload  Watching for file changes with StatReloader
INFO 2021-06-07 13:18:12,821 basehttp  "GET / HTTP/1.1" 200 17776
WARNING 2021-06-07 13:18:19,725 log  Not Found: /info
WARNING 2021-06-07 13:18:19,726 basehttp  "GET /info HTTP/1.1" 404 2541
INFO 2021-06-07 13:20:04,970 basehttp  "GET / HTTP/1.1" 200 17776
INFO 2021-06-07 13:20:06,975 basehttp  "GET /house/ HTTP/1.1" 200 12460
INFO 2021-06-07 13:20:07,120 basehttp  "GET /static/js/send_param.js HTTP/1.1" 200 326
INFO 2021-06-07 13:20:09,424 basehttp  "GET /accounts/logout/ HTTP/1.1" 200 1500
INFO 2021-06-07 13:20:11,335 basehttp  "GET /house/admin/ HTTP/1.1" 302 0
INFO 2021-06-07 13:20:11,371 basehttp  "GET /house/admin/login/?next=/house/admin/ HTTP/1.1" 200 2308
INFO 2021-06-07 13:20:11,429 basehttp  "GET /static/admin/css/login.css HTTP/1.1" 200 1185
INFO 2021-06-07 13:20:24,918 basehttp  "GET /house/info HTTP/1.1" 301 0
INFO 2021-06-07 13:20:24,929 basehttp  "GET /house/info/ HTTP/1.1" 200 123
INFO 2021-06-07 13:20:30,461 basehttp  "GET /house/admin/login/?next=/house/admin/ HTTP/1.1" 200 2308
INFO 2021-06-07 13:23:19,577 autoreload  Watching for file changes with StatReloader
INFO 2021-06-07 13:23:20,555 basehttp  "GET /house/admin/login/?next=/house/admin/ HTTP/1.1" 200 2308
INFO 2021-06-07 13:23:28,866 basehttp  "GET /house/ HTTP/1.1" 302 0
INFO 2021-06-07 13:23:28,896 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2758
INFO 2021-06-07 13:23:53,936 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2755
INFO 2021-06-07 13:23:54,000 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 304 0
INFO 2021-06-07 13:24:05,272 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2768
INFO 2021-06-07 13:24:05,319 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 304 0
INFO 2021-06-07 13:25:29,943 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2765
INFO 2021-06-07 13:25:30,008 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 304 0
INFO 2021-06-07 13:25:45,196 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2762
INFO 2021-06-07 13:25:45,266 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 304 0
INFO 2021-06-07 13:25:53,389 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2759
INFO 2021-06-07 13:25:53,479 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 304 0
INFO 2021-06-07 13:26:26,938 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2768
INFO 2021-06-07 13:26:27,021 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 304 0
INFO 2021-06-07 13:26:29,438 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2768
INFO 2021-06-07 13:26:29,513 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 304 0
INFO 2021-06-07 13:26:31,769 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2768
INFO 2021-06-07 13:26:36,556 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2768
INFO 2021-06-07 13:26:36,748 basehttp  "GET /static/css/main.css HTTP/1.1" 200 596
INFO 2021-06-07 13:26:36,824 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 200 287630
WARNING 2021-06-07 13:26:37,172 log  Not Found: /favicon.ico
WARNING 2021-06-07 13:26:37,173 basehttp  "GET /favicon.ico HTTP/1.1" 404 2562
INFO 2021-06-07 13:26:44,760 autoreload  Watching for file changes with StatReloader
INFO 2021-06-07 13:26:46,284 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2768
INFO 2021-06-07 13:26:46,431 basehttp  "GET /static/css/main.css HTTP/1.1" 200 596
INFO 2021-06-07 13:26:46,507 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 200 287630
WARNING 2021-06-07 13:26:46,928 log  Not Found: /favicon.ico
WARNING 2021-06-07 13:26:46,929 basehttp  "GET /favicon.ico HTTP/1.1" 404 2562
INFO 2021-06-07 13:27:46,778 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2786
INFO 2021-06-07 13:27:46,858 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 200 287630
INFO 2021-06-07 13:27:46,861 basehttp  "GET /static/css/main.css HTTP/1.1" 200 596
WARNING 2021-06-07 13:27:47,238 log  Not Found: /favicon.ico
WARNING 2021-06-07 13:27:47,239 basehttp  "GET /favicon.ico HTTP/1.1" 404 2562
INFO 2021-06-07 13:27:51,395 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2786
INFO 2021-06-07 13:27:51,505 basehttp  "GET /static/css/main.css HTTP/1.1" 200 596
INFO 2021-06-07 13:27:51,511 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 200 287630
WARNING 2021-06-07 13:27:51,817 log  Not Found: /favicon.ico
WARNING 2021-06-07 13:27:51,818 basehttp  "GET /favicon.ico HTTP/1.1" 404 2562
INFO 2021-06-07 13:28:00,194 autoreload  Watching for file changes with StatReloader
INFO 2021-06-07 13:28:00,733 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2786
INFO 2021-06-07 13:28:00,918 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 200 287630
INFO 2021-06-07 13:28:00,920 basehttp  "GET /static/css/main.css HTTP/1.1" 200 596
WARNING 2021-06-07 13:28:01,255 log  Not Found: /favicon.ico
WARNING 2021-06-07 13:28:01,256 basehttp  "GET /favicon.ico HTTP/1.1" 404 2562
INFO 2021-06-07 13:28:48,842 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2765
INFO 2021-06-07 13:28:49,011 basehttp  "GET /static/css/main.css HTTP/1.1" 200 596
INFO 2021-06-07 13:28:49,034 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 200 287630
WARNING 2021-06-07 13:28:49,744 log  Not Found: /favicon.ico
WARNING 2021-06-07 13:28:49,745 basehttp  "GET /favicon.ico HTTP/1.1" 404 2562
INFO 2021-06-07 13:29:16,436 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2771
INFO 2021-06-07 13:29:16,577 basehttp  "GET /static/css/main.css HTTP/1.1" 200 596
INFO 2021-06-07 13:29:16,583 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 200 287630
WARNING 2021-06-07 13:29:18,039 log  Not Found: /favicon.ico
WARNING 2021-06-07 13:29:18,040 basehttp  "GET /favicon.ico HTTP/1.1" 404 2562
INFO 2021-06-07 13:29:19,950 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2771
INFO 2021-06-07 13:29:20,027 basehttp  "GET /static/css/main.css HTTP/1.1" 200 596
INFO 2021-06-07 13:29:20,035 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 200 287630
WARNING 2021-06-07 13:29:20,518 log  Not Found: /favicon.ico
WARNING 2021-06-07 13:29:20,519 basehttp  "GET /favicon.ico HTTP/1.1" 404 2562
INFO 2021-06-07 13:29:36,788 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2785
INFO 2021-06-07 13:29:36,886 basehttp  "GET /static/css/main.css HTTP/1.1" 200 596
INFO 2021-06-07 13:29:36,890 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 200 287630
WARNING 2021-06-07 13:29:37,209 log  Not Found: /favicon.ico
WARNING 2021-06-07 13:29:37,210 basehttp  "GET /favicon.ico HTTP/1.1" 404 2562
INFO 2021-06-07 13:29:54,770 autoreload  Watching for file changes with StatReloader
INFO 2021-06-07 13:29:55,275 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2806
INFO 2021-06-07 13:29:55,468 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 200 287630
INFO 2021-06-07 13:29:55,469 basehttp  "GET /static/css/main.css HTTP/1.1" 200 596
WARNING 2021-06-07 13:29:55,873 log  Not Found: /favicon.ico
WARNING 2021-06-07 13:29:55,874 basehttp  "GET /favicon.ico HTTP/1.1" 404 2562
INFO 2021-06-07 13:29:58,445 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2806
INFO 2021-06-07 13:29:58,628 basehttp  "GET /static/css/main.css HTTP/1.1" 200 596
INFO 2021-06-07 13:29:58,635 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 200 287630
WARNING 2021-06-07 13:29:59,075 log  Not Found: /favicon.ico
WARNING 2021-06-07 13:29:59,076 basehttp  "GET /favicon.ico HTTP/1.1" 404 2562
INFO 2021-06-07 13:30:49,066 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2851
INFO 2021-06-07 13:30:49,243 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 200 287630
INFO 2021-06-07 13:30:49,253 basehttp  "GET /static/css/main.css HTTP/1.1" 200 596
WARNING 2021-06-07 13:30:49,592 log  Not Found: /favicon.ico
WARNING 2021-06-07 13:30:49,593 basehttp  "GET /favicon.ico HTTP/1.1" 404 2562
INFO 2021-06-07 13:31:43,333 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2849
INFO 2021-06-07 13:31:43,467 basehttp  "GET /static/css/main.css HTTP/1.1" 200 596
INFO 2021-06-07 13:31:43,478 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 200 287630
WARNING 2021-06-07 13:31:43,805 log  Not Found: /favicon.ico
WARNING 2021-06-07 13:31:43,806 basehttp  "GET /favicon.ico HTTP/1.1" 404 2562
INFO 2021-06-07 13:31:55,222 basehttp  "GET /house/info/ HTTP/1.1" 200 123
WARNING 2021-06-07 13:31:55,443 log  Not Found: /favicon.ico
WARNING 2021-06-07 13:31:55,446 basehttp  "GET /favicon.ico HTTP/1.1" 404 2562
INFO 2021-06-07 13:36:44,905 basehttp  "GET / HTTP/1.1" 200 17776
INFO 2021-06-07 13:36:46,867 basehttp  "GET /house/ HTTP/1.1" 302 0
INFO 2021-06-07 13:36:46,916 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2849
INFO 2021-06-07 13:36:47,034 basehttp  "GET /static/css/main.css HTTP/1.1" 304 0
INFO 2021-06-07 13:36:48,649 basehttp  "GET /house/info/ HTTP/1.1" 200 7366
INFO 2021-06-07 13:44:33,973 basehttp  "GET /house/info/ HTTP/1.1" 200 7362
INFO 2021-06-07 13:44:34,123 basehttp  "GET /static/css/main.css HTTP/1.1" 304 0
INFO 2021-06-07 13:44:34,332 autoreload  D:\SynologyDrive\my_smart_home\house\core\views.py changed, reloading.
INFO 2021-06-07 13:44:37,645 autoreload  Watching for file changes with StatReloader
INFO 2021-06-07 13:44:38,651 basehttp  "GET /house/info/ HTTP/1.1" 200 7442
INFO 2021-06-07 13:46:17,748 basehttp  "GET /house/info/ HTTP/1.1" 200 7442
INFO 2021-06-07 13:46:17,828 basehttp  "GET /static/css/main.css HTTP/1.1" 304 0
INFO 2021-06-07 13:47:56,823 basehttp  "GET /house/info/ HTTP/1.1" 200 5531
INFO 2021-06-07 13:47:57,363 autoreload  D:\SynologyDrive\my_smart_home\house\core\views.py changed, reloading.
INFO 2021-06-07 13:48:00,193 autoreload  Watching for file changes with StatReloader
INFO 2021-06-07 13:48:00,753 basehttp  "GET /house/info/ HTTP/1.1" 200 5535
INFO 2021-06-07 13:49:08,629 basehttp  "GET /house/info/ HTTP/1.1" 200 5467
INFO 2021-06-07 13:49:08,896 basehttp  "GET /static/css/main.css HTTP/1.1" 200 596
INFO 2021-06-07 13:49:09,033 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 200 287630
WARNING 2021-06-07 13:49:09,448 log  Not Found: /favicon.ico
WARNING 2021-06-07 13:49:09,449 basehttp  "GET /favicon.ico HTTP/1.1" 404 2562
INFO 2021-06-07 13:49:31,675 basehttp  "GET /house/info/ HTTP/1.1" 200 5467
INFO 2021-06-07 13:49:31,774 basehttp  "GET /static/css/main.css HTTP/1.1" 200 596
INFO 2021-06-07 13:49:31,783 basehttp  "GET /static/selection_avto/jquery/jquery-3.5.1.js HTTP/1.1" 200 287630
WARNING 2021-06-07 13:49:32,129 log  Not Found: /favicon.ico
WARNING 2021-06-07 13:49:32,131 basehttp  "GET /favicon.ico HTTP/1.1" 404 2562
INFO 2021-06-07 13:53:51,380 basehttp  "GET / HTTP/1.1" 200 17776
INFO 2021-06-07 13:53:53,942 basehttp  "GET /house/ HTTP/1.1" 302 0
INFO 2021-06-07 13:53:53,974 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2849
INFO 2021-06-07 13:53:54,117 basehttp  "GET /static/css/main.css HTTP/1.1" 304 0
INFO 2021-06-07 13:53:55,593 basehttp  "GET /house/info/ HTTP/1.1" 200 4509
INFO 2021-06-07 16:48:24,795 autoreload  Watching for file changes with StatReloader
INFO 2021-06-07 16:48:29,791 basehttp  "GET / HTTP/1.1" 200 17776
WARNING 2021-06-07 16:48:39,519 log  Not Found: /house/i/
WARNING 2021-06-07 16:48:39,520 basehttp  "GET /house/i/ HTTP/1.1" 404 4842
INFO 2021-06-07 16:48:45,063 basehttp  "GET /house/info/ HTTP/1.1" 200 4509
INFO 2021-06-07 16:48:45,138 basehttp  "GET /static/css/main.css HTTP/1.1" 304 0
INFO 2021-06-07 16:49:31,868 autoreload  D:\SynologyDrive\my_smart_home\house\core\views.py changed, reloading.
INFO 2021-06-07 16:49:34,805 autoreload  Watching for file changes with StatReloader
INFO 2021-06-07 16:49:35,950 basehttp  "GET /house/info/ HTTP/1.1" 200 4509
INFO 2021-06-08 16:05:46,561 autoreload  Watching for file changes with StatReloader
INFO 2021-06-08 16:05:56,797 basehttp  "GET / HTTP/1.1" 200 17776
INFO 2021-06-08 16:05:58,667 basehttp  "GET /house/ HTTP/1.1" 302 0
INFO 2021-06-08 16:05:58,720 basehttp  "GET /accounts/login/?next=/house/ HTTP/1.1" 200 2849
INFO 2021-06-08 16:05:58,834 basehttp  "GET /static/css/main.css HTTP/1.1" 304 0
INFO 2021-06-08 16:06:00,897 basehttp  "GET /house/info/ HTTP/1.1" 200 4509
INFO 2021-06-08 16:06:28,602 autoreload  Watching for file changes with StatReloader
